### ISSUE TITLE
Associations need to be passed in as arrays

### ISSUE THREAD

**Issue by darkstego** [sirupsen/airrecord#11]
In the example you provide 
`tea = Tea.find('rec849829')`
`Brew.create("Tea" => tea, "Temperature" => "80", "Time" => "4m", "Rating" => "5")`
This won't work because the tea variable passed in will always go through a map method as part of the serialization for any association. you need to provide it as single element array for it to work.

**Comment by sirupsen** [comment]
Yeah, good point! Want to submit a patch for this?

**Comment by darkstego** [comment]
I was unsure how you wanted this to be handled. Do you want to allow non
array inputs?

**Comment by sirupsen** [comment]
Yep
