### ISSUE TITLE
Support passing options into the create call

### ISSUE THREAD

**Issue by theblang** [sirupsen/airrecord#13]
I noticed that in order to turn auto conversion on for data you need to pass `typecast: true`in the request. In order to do that through the airrecord wrapper we'd need a way to send it to the create call.

From my base's API documentation: 

> Airtable API performs automatic data conversion from string values if typecast parameter is passed in (click for example). Automatic conversion is disabled by default to ensure data integrity, but it may be helpful for integrating with 3rd party data sources.

**Comment by sirupsen** [comment]
Do you think it'd make sense to enable that by default?

**Comment by mattblang** [comment]
I would probably say no. Since you have to be explicit about it in the POST request, should probably likewise be explicit about it in the Ruby wrapper.

**Comment by sirupsen** [comment]
👍 would accept a PR that does this
