### ISSUE TITLE
Maybe we can add some of the Mongoid-esque

### ISSUE THREAD

**Issue by jfrux** [sirupsen/airrecord#25]
Would be sick if we could use our model files to determine the actual schema itself similar to Mongoid.

Or have optional `includes` that we can add to them like Timestamps.

Thinking about this a lot lately.

Not sure if that would even matter.

I'm using it to generate static sites so probably wouldn't ever be a use case for people that are hosting their sites with Rails or something but who knows.

**Comment by sirupsen** [comment]
Unfortunately, Airtable hasn't exposed their schema via the API despite asking for years :( We may introduce typing the schema into the `Table` in 1.x, is that something you'd be interested in exploring with us? Apologize for the delay.
