### ISSUE TITLE
Airrecord::Error Exception: Unable to save a new record

### ISSUE THREAD

**Issue by JalenOng** [sirupsen/airrecord#48]
Hi, I tried to write to Airtable but got an error. I'd appreciate if there is more information on the error rather than just:

Airrecord::Error Exception: Unable to save a new record

What I did was tried to byebug into a controller and did this:

comp = Result.new("Month" => "Nov", "Number of Paying Residents" => 233)
comp.save

I could read the table alright but had trouble writing to it. Please advise. Thanks!

**Comment by sirupsen** [comment]
Please upgrade to 1.0.0 which will do the right thing here.

**Comment by JalenOng** [comment]
Solved after upgrading. Thanks!
