### ISSUE TITLE
Add in some utilities to make Airrecord play well with Rails Form Helpers

### ISSUE THREAD

**Issue by dkolb** [sirupsen/airrecord#52]
I have this module I use to patch the `Airrecord::Table` class that let's me leverage Rails form helpers more directly.

https://gist.github.com/dkolb/9a4a4794b1deacfd9043a4372ae490ab

I was wondering if you'd be interested in me opening a pull request to add these methods directly onto the Table class?

**Comment by sirupsen** [comment]
@dkolb I'm not sure it belongs in core here. I'd prefer that as a separate gem extension that we can link to in the README. How does that sound to you?

**Comment by dkolb** [comment]
Sounds great.  I have some vacation coming up so once I finish the side project that inspired this code, I'll work it up.  I'll be back in touch once I have the gem ready.  :-)

Closing this issue in the meantime.
