### ISSUE TITLE
How to make Airtable run filters

### ISSUE THREAD

**Issue by uzorjchibuzor** [sirupsen/airrecord#58]
The issue I want to raise and I am not certain it is a new one but I want to know if there is a provision that makes Airtable run the filter operation instead of the way Airrecord currently (I think) by getting the whole table then running filter on table. It takes a lot of time to return results.

Thank you

**Comment by sirupsen** [comment]
This is already the case. Airrecord does not have a filter implementation and uses the server-side one from Airtable. If this is a performance problem, I think you'll need to take it up with them!
