### ISSUE TITLE
ArgumentError: wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by fccoelho7** [sirupsen/airrecord#63]
Hey guys, I'm having some issues when trying to use that gem, like this below:

```ruby
[8] pry(main)> m = Airrecord.table("key", "app", "Member")
=> #<Class:0x007fee2677a710>
[9] pry(main)> m.all
ArgumentError: wrong number of arguments (given 1, expected 0)
from /Users/fabiocoelho/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:505:in `initialize'
```

Same is occurring with all methods, like _find_, _update_ etc.

Anyone?

**Comment by fccoelho7** [comment]
Unfortunately it looks like net-http-persisten introduced some breaking changes in its 3.0.0 release, making Faraday incompatible.

Ref.: https://github.com/lostisland/faraday/issues/617

**Comment by sirupsen** [comment]
Looks like this was fixed in Farday with a version requirement
