### ISSUE TITLE
FilterByFormula Using Linked Record

### ISSUE THREAD

**Issue by uzorjchibuzor** [sirupsen/airrecord#65]
This is not an issue, more like a call for help.

So I have two tables, Project Reviews and Students. The Project reviews tables has a column that is linked to the student that submitted the review. When I pull all the records, the Student field is an array containing the id of the student that submitted the Review.

Now, I am trying to retrieve records submitted by a particular student and I kept getting an empty array.

Here is what I tried:
```
find_airrecord_table_by_name('Project Reviews').all(filter: "Student = '[#{student.id}]'")```

**Comment by Meekohi** [comment]
AFAIK, surprisingly, there isn't a good way to do this with AirTable's API. Most of the approaches I've seen involve concat'ing the array values with a separator down into a string and then doing a substring match -- pretty horrifying stuff!

See https://community.airtable.com/t/filtering-rollup-fields-through-the-api/1287/10

**Comment by Meekohi** [comment]
Sorry I misread this originally. I think the right syntax is more like:

$Contact.all(filter: '{Student} = "STUDENT_ID"')

**Comment by uzorjchibuzor** [comment]
Let me show you the complete method. 
```
  def obtain_projects_reviews_test(student_id)
    find_airrecord_table_by_name('Project Reviews').all(filter: "Student =  'student_id'")
  end
```
Here is a sample of how the record is ` @fields={"Project"=>["XXXXXXX"], "Enjoyment"=>"4", "Learning"=>"4", "Working Days to Completion (Incl. Readings)"=>3, "Extra Support?"=>"No", "Student"=>["XXXXXXXXX"], "Github Repo"=>"https://github.com/xxx/xxx", "Live Project"=>"https://raw.g...`

**Comment by uzorjchibuzor** [comment]
AYCS, The Student field is an array of the student's id. That is where my problem is, I can filter with regular values alright, e.g (filter: '{Learning} = "4"') which works fine. The problem comes when I want to use a linked record as the filter parameter.

**Comment by Meekohi** [comment]
Yeah, banged my head against this for another 30 min but I'm stumped. Airtable's API is so bad :'( Would have thought something like this would work at least:

`$Company.all(filter: "SEARCH( 'recOBitclZfoCPyH1', ARRAYJOIN(People) ) >= 0")`

**Comment by uzorjchibuzor** [comment]
The API is limited. I will give your idea a trial and tinker with it a bit. I might have to use ruby to filter the records myself but that is not very performant. Thank you for your help.
