### ISSUE TITLE
Please yank v0.1.0 gem and update faraday dependency

### ISSUE THREAD

**Issue by kenaniah** [sirupsen/airrecord#69]
`faraday` v1.0.0 has been released. This causes a huge issue for `airrecord` when another gem depends on `faraday ~> 1.0` as the latest compatible version of `airrecord` available is v0.1.0 from 2016(!). This is due to the change in the gem spec that occurred in https://github.com/sirupsen/airrecord/commit/86d724057e6eeb6d8503e532b985ac0934596013#diff-90d0f9505c23adb819f70496d486e625.

Prior to this change (and in the v0.1.0 version of the gem), the `faraday` dependency was not version-locked, which allows bundler to use the old version of `airrecord` when attempting to resolve dependencies.

**Comment by sirupsen** [comment]
Fixed in 1.0.5
