### ISSUE TITLE
ruby 3 incompatibility

### ISSUE THREAD

**Issue by courtsimas** [sirupsen/airrecord#79]
Due to the previously-deprecated way args are passed in and mixed with kwargs, this is now throwing a ruby 3 error: https://github.com/sirupsen/airrecord/blob/master/lib/airrecord/faraday_rate_limiter.rb#L9

Any chance you guys can update this gem to work with the new kwarg standards?

**Comment by sirupsen** [comment]
Please submit a PR and I'll merge and release :)

**Comment by courtsimas** [comment]
@sirupsen done! https://github.com/sirupsen/airrecord/pull/80

**Comment by sirupsen** [comment]
Fixed in master, use 1.0.6
