### ISSUE TITLE
Create transparently on save

### ISSUE THREAD

**Issue by sirupsen** [sirupsen/airrecord#8]
If a new record has been instantiated and you call `#save`, instead of raising, we should consider just calling `#create` inline.

**Comment by sirupsen** [comment]
@Meekohi or @chrisfrank any of you interested in doing this for 1.0.0?

**Comment by sirupsen** [comment]
Bump ^, this is the last backwards incompatible change I can think of for 1.0.0. If we get this in, I think we should be good to cut 1.0 :)

**Comment by chrisfrank** [comment]
Fixed in #43
