### ISSUE TITLE
Ruby 3 compatible

### ISSUE THREAD

**Issue by dudo** [sirupsen/airrecord#82]
Tried to update my app to ruby 3 but the airrecord gem depends on an older version of faraday which depends on an older version of net-http-persistent which does not work with ruby 3 Net::HTTP. 

Any effort to have ruby 3 compatibility already? or should I submit a PR?

**Comment by sirupsen** [comment]
I think fixed with allowing faraday 2 now in master?
https://github.com/sirupsen/airrecord/commit/a079e877454a2fb71e94276e4075188e8df99618
