### ISSUE TITLE
Faraday::Error - :net_http_persistent is not registered on Faraday::Adapter:

### ISSUE THREAD

**Issue by cromulus** [sirupsen/airrecord#89]
New error in v1.0.8.

**Comment by pjmartorell** [comment]
The issue appears after upgrading `airrecord` and its dependencies, specifically Faraday, which probably have been upgraded to `2.2.0`, which requires installing Faraday adapters as separate gems (see [this](https://github.com/lostisland/faraday/blob/main/UPGRADING.md#thats-great-what-should-i-change-in-my-code-immediately-after-upgrading) for upgrading instructions). I tried to add `gem 'faraday-net_http_persistent'` to my `Gemfile` but it seems there is another compatibility issue with `airrecord` that raises an error. To circumvent the issue, I suggest you fix the Faraday version you were previously using, i.e. `gem 'faraday', '1.10.0'`

**Comment by pjmartorell** [comment]
I finally fixed the issue just adding the following to my `Gemfile`:
`gem 'faraday-net_http_persistent', '~> 2.0'`

**Comment by sirupsen** [comment]
Couldn't we just add `faraday-net_http_persistent` to the Gemspec, or would that cause problems with Faraday < 2?

**Comment by pjmartorell** [comment]
> Couldn't we just add `faraday-net_http_persistent` to the Gemspec, or would that cause problems with Faraday < 2?

Faraday < 2 already includes the adapter, so adding `faraday-net_http_persistent` gem, in the best-case scenario, would probably overwrite the configuration of adapter, it might work but I haven't tried it. I don't see that `faraday-net_http_persistent` has any restriction in the Gemspec regarding faraday, so if it's correct it should be compatible with all faraday versions.

Alternatively, you could release a new version of `airrecord` setting Faraday as `~> 2.0` and `faraday-net_http_persistent` in the `gemspec`.

**Comment by sirupsen** [comment]
Thanks @pjmartorell in master, and released as 1.0.9
