### ISSUE TITLE
Ruby 3.0.3 | wrong number of arguments in faraday_rate_limiter.rb:in initialize

### ISSUE THREAD

**Issue by pyveslg** [sirupsen/airrecord#92]
Hello 👋 

First of all thanks for your great work with the gem! 🙏 

I am trying to upgrade my app to ruby 3 (and get ready for rails 7) and make it work with the airrecord gem.

👉 I am however facing an issue while calling a method on my Airrecord Table (called `SyllabusAirtableClient` in my example) related to a wrong number of arguments passed when the initialize method of FaradayRateLimiter Class is called.

![CleanShot 2022-04-21 at 14 25 27@2x](https://user-images.githubusercontent.com/8135012/164457620-e4bb1fb2-4e07-47fc-8190-85946debe64f.png)

I understood that ruby 3 introduces an incompatibility with previous versions with positional arguments and keyword arguments. Maybe it is linked to this?
I looks like very similar to this fixed issue  https://github.com/sirupsen/airrecord/issues/79. I tried with version 1.0.6 with no further success.

👉 I am currently using `Airrecord 1.0.8`. When upgrading to `Airrecord 1.0.9`, I am also facing same issue as above, plus the following warning at launching my rails server. 
![CleanShot 2022-04-21 at 14 15 04@2x](https://user-images.githubusercontent.com/8135012/164455994-1806a473-0d90-4c28-bceb-7e05f2c7b622.png)

I did looked at the following similar issues but it does not seem to help avoiding the warning :  https://github.com/sirupsen/airrecord/issues/89.
When removing the airrecord gem, I do not have the warnings above.

I am not really used to raise issue on github so I hope this issue is clear enough. If not, please, let me know so that I can try to be more explicit.
When you have some time, your help or ideas would be much appreciated! Thanks!

**Comment by sirupsen** [comment]
Hi Pierre, can you reproduce this outside of your large environment in a
single Ruby file? That would make it easier to help! Thanks

Simon
https://sirupsen.com/

**Comment by pyveslg** [comment]
Hi Simon,

Sure! Here is the code tested in a single ruby file. 

```
require 'airrecord'

Airrecord.api_key = ENV["AIRTABLE_APIKEY"]

class SyllabusAirtableClient < Airrecord::Table
  self.base_key = ENV["SYLLABUS_AIRTABLE_BASE"]
  self.table_name = "Contacts"
end

SyllabusAirtableClient.all
```

And the message obtained is the following:
```
/Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/airrecord-1.0.9/lib/airrecord/faraday_rate_limiter.rb:9:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
  from /Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-0.17.5/lib/faraday/middleware.rb:21:in `new'
  from /Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-0.17.5/lib/faraday/middleware.rb:21:in `new'
  from /Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-0.17.5/lib/faraday/rack_builder.rb:48:in `build'
  from /Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-0.17.5/lib/faraday/rack_builder.rb:167:in `block in to_app'
  from /Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-0.17.5/lib/faraday/rack_builder.rb:167:in `each'
  from /Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-0.17.5/lib/faraday/rack_builder.rb:167:in `inject'
  from /Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-0.17.5/lib/faraday/rack_builder.rb:167:in `to_app'
  from /Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-0.17.5/lib/faraday/rack_builder.rb:156:in `app'
  from /Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-0.17.5/lib/faraday/rack_builder.rb:143:in `build_response'
  from /Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-0.17.5/lib/faraday/connection.rb:387:in `run_request'
  from /Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-0.17.5/lib/faraday/connection.rb:138:in `get'
  from /Users/~~~~~~~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/airrecord-1.0.9/lib/airrecord/table.rb:80:in `records'
  from air_record_test.rb:11:in `<main>'
```

Please, let me know if that's make more sense like this or if you need any further details.
Thank you so much!

**Comment by sirupsen** [comment]
What's your Faraday version?

**Comment by pyveslg** [comment]
I have the latest available version `0.17.5`

**Comment by sirupsen** [comment]
Took a quick look—0.17.5 is not the latest version, but is the latest tag. I think Faraday is maintaining three semantic version trees (0.x, 1.x, and 2.x). I've dropped compatibility with 0.x in Airrecord in the 1.0.10 release.

Try to install a newer version of Faraday, and it should work

**Comment by pyveslg** [comment]
Indeed. So sorry about having missed that...
I tried it and it works as expected!
Thanks a lot Simon for your great support and work.
