### ISSUE TITLE
Faraday rate limit argument issue

### ISSUE THREAD

**Issue by vietqhoang** [sirupsen/airrecord#97]
# Relevant dependencies

* `ruby` version `3.2.0`
* `airrecord` version `1.0.10`
* `faraday` version `1.10.2`

# Problem

The following error is raised when method chain `Airrecord.table.create` is called.

```
ArgumentError: wrong number of arguments (given 2, expected 1)
```

The error is sourced from `[GEM_ROOT]/gems/airrecord-1.0.10/lib/airrecord/faraday_rate_limiter.rb:9:in 'initialize'`.

When running the application in Ruby 3.1.2 the issue does not exist.

Reviewing the [Ruby 3.2.0 changes](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/) it looks like this may be related to `ruby2_keywords` changes.

**Comment by Keqi** [comment]
Hey, we're experiencing the same issue. Any timeline to fix it? 🙏

**Comment by Meekohi** [comment]
@Keqi I don't think anyone is actively working on this gem currently -- PRs welcome.

**Comment by vietqhoang** [comment]
Rounding back to this.

The recent faraday 1.10.3 update has addressed this issue by implementing the ruby2_keyword shim to address the keyword argument incompatibility in Ruby 3.

See the following:

* https://github.com/lostisland/faraday/releases/tag/v1.10.3
* https://github.com/lostisland/faraday/pull/1483 (Specifically, [this change](https://github.com/timrogers/faraday/blob/012f510da283c874aa651709259754f17a260ebd/lib/faraday/dependency_loader.rb#L18))

The error goes away once the faraday dependency has updated to at least 1.10.3. This can be done in your project with `bundle update faraday`.

Closing this since a solution has been identified.
